// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdG6mrx1C58QMWWfIfXiK1M6A06ECXE38',
    appId: '1:420411110177:web:d9f8d64b4ddbb0eae20460',
    messagingSenderId: '420411110177',
    projectId: 'smart-farm-flutter',
    authDomain: 'smart-farm-flutter.firebaseapp.com',
    storageBucket: 'smart-farm-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbxVW1NZ97sFjYqH_LY_yeatIynBt2mIY',
    appId: '1:420411110177:android:5983492d048603b8e20460',
    messagingSenderId: '420411110177',
    projectId: 'smart-farm-flutter',
    storageBucket: 'smart-farm-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiCPU6LW7kpBDnjXvCB-oPnUNFsc9F-3A',
    appId: '1:420411110177:ios:49042ffec6ac2cf4e20460',
    messagingSenderId: '420411110177',
    projectId: 'smart-farm-flutter',
    storageBucket: 'smart-farm-flutter.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiCPU6LW7kpBDnjXvCB-oPnUNFsc9F-3A',
    appId: '1:420411110177:ios:49042ffec6ac2cf4e20460',
    messagingSenderId: '420411110177',
    projectId: 'smart-farm-flutter',
    storageBucket: 'smart-farm-flutter.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdG6mrx1C58QMWWfIfXiK1M6A06ECXE38',
    appId: '1:420411110177:web:e4d39e4f4f98a8ede20460',
    messagingSenderId: '420411110177',
    projectId: 'smart-farm-flutter',
    authDomain: 'smart-farm-flutter.firebaseapp.com',
    storageBucket: 'smart-farm-flutter.firebasestorage.app',
  );
}
